[package]
name = "repository"
version = "0.1.0"
authors = ["ArakiTakaki <araki_takaki@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
